### ISSUE TITLE
glitched Aetherium cloak

### ISSUE THREAD

**Issue by JosephGallagher2001** [tyon2006/AetheriumAshenArmor#5]
![2020-08-01_12 20 14](https://user-images.githubusercontent.com/61439639/89105708-8a5ab180-d3f1-11ea-8149-a710b9c2463a.png)
there seems to be an issue with the Aetherium ashen cloak gloves to not seeming move in sync with the player punch animation. I posted a similar issue back in March regarding the normal ashen cloak (the embers rekindled version), and it has since been fixed in EmbersRekindled-hotfix 1.14, but this glitch is still present in Aetherium Ashen Armor-Release-1.12.2-1.1.1.jar. if you could take a look at this, Tyon, that would be helpful.

**Comment by tyon2006** [comment]
Hey! I just caught up with Bord about the bug and he actually left the old code in there to keep other dependent mods working. So, I was not yet referencing his new code. My latest release is now referencing that new code, so lemme know if that fixes it.

I've never been able to produce this glitch myself, so I'll need your feedback to confirm its fixed.

**Comment by JosephGallagher2001** [comment]
ok, thanks man

**Comment by JosephGallagher2001** [comment]
your latest release is this one, right? Aetherium Ashen Armor-Release-1.12.2-1.2.1.jar. Just checking. also, thanks for taking a look at this.

**Comment by JosephGallagher2001** [comment]
I just tested the fix, and it appears to be working.
