### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by KamiSami** [tyon2006/AetheriumAshenArmor#6]
Hi, i am pretty new to this mod, wanted to give it a try but i realized that server has issues with it, i do not know what this means or if it's incompatibility or something, but here. https://pastebin.com/Vk0AXLap

**Comment by tyon2006** [comment]
Hmm, yeah. Looks like a new server problem. I'll take a look soon.

**Comment by tyon2006** [comment]
Go check out the new version I just posted. Should've fixed it 👍

**Comment by KamiSami** [comment]
I believe it works now, thanks!

**Comment by tyon2006** [comment]
Awesome! Thanks for the report.
